environments:
  minikube:
    values:
      - minikube.yaml
---
repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

---
releases:
  - name: prometheus-operator-crds
    namespace: monitoring
    chart: prometheus-community/prometheus-operator-crds
    version: 25.0.1
  - name: kube-prometheus-stack
    namespace: monitoring
    chart: prometheus-community/kube-prometheus-stack
    version: 80.4.1
